### สร้างโพสต์ใหม่
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "My first post",
  "content": "Hello world!"
}

### ดึงโพสต์ทั้งหมด
GET http://localhost:8080/posts

### ดึงโพสต์ด้วย id = 3
GET http://localhost:8080/posts/3

### แก้ไขโพสต์ id = 3
PUT http://localhost:8080/posts/3
Content-Type: application/json


{
  "title": "Updated post title",
  "content": "Updated content here."
}

### ลบโพสต์ id
DELETE http://localhost:8080/posts/1

### สร้างคอมเมนต์ในโพสต์ id
POST http://localhost:8080/posts/2/comments
Content-Type: application/json

{
  "authorName": "Alice",
  "content": "Great post!"
}

### ดึงโพสต์ พร้อมคอมเมนต์
GET http://localhost:8080/posts/2
